# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 21 Feb 2019 18:09:30 +0000
*               @ALL          1
*               @user         8
