<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: kalekdan
 * Date: Sat, 23 Feb 2019 09:50:22 -0600
 */

$conf['title'] = 'Ensulasia';
$conf['start'] = 'Welcome to Ensulasia';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
